# Generated by Django 4.1.2 on 2022-10-11 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4e53c45-17e0-4de0-be1c-6b8d5d57b905'), primary_key=True, serialize=False, unique=True),
        ),
    ]
