# Generated by Django 4.1.2 on 2022-10-11 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0002_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd4e7367-4f43-448d-991b-ae33a286fa90'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e43b956-ba6c-4adc-87ec-6e999f3f9876'), primary_key=True, serialize=False, unique=True),
        ),
    ]
