# Generated by Django 4.1.2 on 2022-10-11 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0003_alter_feedbacks_id_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='message',
            field=models.CharField(default='Example', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25563cbe-cc18-4b7d-9721-88ec44a76359'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e62aeb09-2bf7-412d-b904-94505ff0c760'), primary_key=True, serialize=False, unique=True),
        ),
    ]
